**Step-1**
**import packages**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# pandas is used for dataframe
# numpy is used for numerical calculation
# matplotlib.pyplot is used for graph and plot
# seaborn is used for graph

**step-2**
**creat a dataframe using list**

**always pass values in list format to Dataframe**

In [4]:
names=['ramesh','suresh','satish']
#pd.DataFrame(data,index,column)
pd.DataFrame(names)

        0
0  ramesh
1  suresh
2  satish

**step-3**
**change index**

In [5]:
nindex=['A','B','C']
pd.DataFrame(names,nindex)

        0
A  ramesh
B  suresh
C  satish

**step-4**
**add column names**

In [6]:
ncol=['Names']
pd.DataFrame(names,nindex,ncol)

    Names
A  ramesh
B  suresh
C  satish

**step 5 data and columm**

In [7]:
names=['Ramesh','Suresh','Mahesh']
ncol=['Names']
pd.DataFrame(names,columns=ncol)

    Names
0  Ramesh
1  Suresh
2  Mahesh

**step-6**
**multiple columns**

In [8]:
names=['Suresh','Ramesh','Satish']
age=[20,22,24]
pd.DataFrame(zip(names,age))

        0   1
0  Suresh  20
1  Ramesh  22
2  Satish  24

In [9]:
nindex=['A','B','C']
cols=['Name','Age']
df=pd.DataFrame(zip(names,age),nindex,cols)
df

     Name  Age
A  Suresh   20
B  Ramesh   22
C  Satish   24

**step 7 - add new column to existing dataframe**

- in above first we have taken data

- then created a dataframe

- now we want to add new data based on requirement

In [10]:
city=['Hyd','Mum','Blr']

In [11]:
df['City']=city

In [12]:
df

     Name  Age City
A  Suresh   20  Hyd
B  Ramesh   22  Mum
C  Satish   24  Blr

In [13]:
df['Marks']=[20,30,40]

In [14]:
df

     Name  Age City  Marks
A  Suresh   20  Hyd     20
B  Ramesh   22  Mum     30
C  Satish   24  Blr     40

**step-8 update the column with new values**

In [15]:
df['Marks']=[200,300,400]

In [16]:
df

     Name  Age City  Marks
A  Suresh   20  Hyd    200
B  Ramesh   22  Mum    300
C  Satish   24  Blr    400

**step-9 create empty dataframe and add the column**

In [17]:
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [18]:
df1['Names']=['Suresh','Ramesh','Satish']
df1

    Names
0  Suresh
1  Ramesh
2  Satish

In [19]:
df1['Age']=[20,22,24]
df1['City']=['Pune','Mum','Hyd']
df1

    Names  Age  City
0  Suresh   20  Pune
1  Ramesh   22   Mum
2  Satish   24   Hyd

**step-10 create a dataframe using dictionary**

In [20]:
d={'Names':['Ramesh','Suresh','Satish'],
   'Age':[20,22,40],
   'City':['Hyd','Mum','Blr']}

In [21]:
pd.DataFrame(d)

    Names  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
2  Satish   40  Blr

In [22]:
d2={'Name':'Suresh',
    'Age':20 }

In [23]:
pd.DataFrame(d2) #this will give error because while using single value or scalar value you must pass index

ValueError: If using all scalar values, you must pass an index

In [ ]:
pd.DataFrame(d2,index=[0])

**step-11 saving the dataframe**

-file handling session
- directory/filename
- filename.text
- we are saving dataframe
- .csv or .xls

In [24]:
df1.to_csv('data.csv')

In [25]:
df1.to_excel('data.xlsx')

In [26]:
df1.to_csv(r'C:\Users\vijay\Documents\NareshIT\numpy\data.csv')

In [27]:
df1.to_excel(r'C:\Users\vijay\Documents\NareshIT\numpy\data.xlsx')

In [28]:
df

     Name  Age City  Marks
A  Suresh   20  Hyd    200
B  Ramesh   22  Mum    300
C  Satish   24  Blr    400

In [29]:
df.loc['0','Marks']=250
df

     Name   Age City  Marks
A  Suresh  20.0  Hyd  200.0
B  Ramesh  22.0  Mum  300.0
C  Satish  24.0  Blr  400.0
0     NaN   NaN  NaN  250.0

In [30]:
df.drop(columns='Age',axis=10)

     Name City  Marks
A  Suresh  Hyd  200.0
B  Ramesh  Mum  300.0
C  Satish  Blr  400.0
0     NaN  NaN  250.0

In [31]:
df

     Name   Age City  Marks
A  Suresh  20.0  Hyd  200.0
B  Ramesh  22.0  Mum  300.0
C  Satish  24.0  Blr  400.0
0     NaN   NaN  NaN  250.0

**step-12 read the dataframe**

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
#in order to read the data
#filename.extenation
#open(test.txt).read()
#open(test.txt,mode=''w).write('hello')
pd.read_csv('data.csv')

   Unnamed: 0   Names  Age  City
0           0  Suresh   20  Pune
1           1  Ramesh   22   Mum
2           2  Satish   24   Hyd

In [34]:
pd.read_excel('data.xlsx')
#pd.read_excel('data.xlsx',engine='openpyxl')

   Unnamed: 0   Names  Age  City
0           0  Suresh   20  Pune
1           1  Ramesh   22   Mum
2           2  Satish   24   Hyd

In [35]:
df

     Name   Age City  Marks
A  Suresh  20.0  Hyd  200.0
B  Ramesh  22.0  Mum  300.0
C  Satish  24.0  Blr  400.0
0     NaN   NaN  NaN  250.0

In [36]:
pd.read_excel('data.xlsx')

   Unnamed: 0   Names  Age  City
0           0  Suresh   20  Pune
1           1  Ramesh   22   Mum
2           2  Satish   24   Hyd

**save the fiel without extra column**

In [37]:
d={'Names':['Ramesh','Suresh','Satish'],
   'Age':[20,22,40],
   'City':['Hyd','Mum','Blr']}

In [38]:
df1=pd.DataFrame(d)
df1

    Names  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
2  Satish   40  Blr

In [39]:
df1.to_csv
pd.read_csv
df1.to_excel
pd.read_excel

<function pandas.io.excel._base.read_excel(io, sheet_name: 'str | int | list[IntStrT] | None' = 0, *, header: 'int | Sequence[int] | None' = 0, names: 'SequenceNotStr[Hashable] | range | None' = None, index_col: 'int | str | Sequence[int] | None' = None, usecols: 'int | str | Sequence[int] | Sequence[str] | Callable[[str], bool] | None' = None, dtype: 'DtypeArg | None' = None, engine: "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb', 'calamine'] | None" = None, converters: 'dict[str, Callable] | dict[int, Callable] | None' = None, true_values: 'Iterable[Hashable] | None' = None, false_values: 'Iterable[Hashable] | None' = None, skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, parse_dates: 'list | dict | bool' = False, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'dict[Hashable, str] | str | None' = None, thousands: 'str | None' = None, decimal: 'str' = '.', comment: 'str | None' = None, skipfooter: 'int' = 0, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>, engine_kwargs: 'dict | None' = None) -> 'DataFrame | dict[IntStrT, DataFrame]'>

In [40]:
df1.to_csv('data1.csv',index=False)# this will not add extra column to csv file when it is saved

In [41]:
pd.read_csv('data1.csv')

    Names  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
2  Satish   40  Blr

In [42]:
df1.to_excel('data1.xlsx')

In [43]:
pd.read_excel('data1.xlsx')

   Unnamed: 0   Names  Age City
0           0  Ramesh   20  Hyd
1           1  Suresh   22  Mum
2           2  Satish   40  Blr

In [44]:
df1['Marks']=[100,200,300]
df1

    Names  Age City  Marks
0  Ramesh   20  Hyd    100
1  Suresh   22  Mum    200
2  Satish   40  Blr    300

**step 13 drop column**

- labels: 'IndexLabel | None' = None,
- axis: 'Axis' = 0,
- index: 'IndexLabel | None' = None,
- columns: 'IndexLabel | None' = None,
- level: 'Level | None' = None,
- inplace: 'bool' = False,
- errors: 'IgnoreRaise' = 'raise',

In [45]:
#if i have to drop a index(row)
#then use the index argument
df1.drop(index=1)

    Names  Age City  Marks
0  Ramesh   20  Hyd    100
2  Satish   40  Blr    300

In [46]:
df1

    Names  Age City  Marks
0  Ramesh   20  Hyd    100
1  Suresh   22  Mum    200
2  Satish   40  Blr    300

In [47]:
df1.drop(columns=['City','Marks'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   40

In [48]:
df1

    Names  Age City  Marks
0  Ramesh   20  Hyd    100
1  Suresh   22  Mum    200
2  Satish   40  Blr    300

In [49]:
df1.drop(index=1)
df1.drop(columns='Marks')
df1

    Names  Age City  Marks
0  Ramesh   20  Hyd    100
1  Suresh   22  Mum    200
2  Satish   40  Blr    300

In [50]:
df1.drop('Marks')#we need to provide axis
df1.drop(1) #if we dont provide argument 1 become label

KeyError: "['Marks'] not found in axis"

In [ ]:
df1

In [ ]:
#we need to provide axis
#axis=0 indicates index
#axis=1 indicates column

In [51]:
df1.drop('Marks',axis=1)

    Names  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
2  Satish   40  Blr

**inplace**

- when we do the operation the result output is not overwriting

- means original dataframe is as it is

- in order to do this give **inplace**

- by default inplace=False

- to do this give inplace =True

In [52]:
df1.drop(columns='Marks',inplace=True)

In [53]:
df1

    Names  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
2  Satish   40  Blr

**step-14 Rename the column**

In [54]:
df1.rename(columns={'Names':'Name'},inplace=True)
df1

     Name  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
2  Satish   40  Blr

In [55]:
d={2:'B'}
df1.rename(d,axis=0,inplace=True)
df1

     Name  Age City
0  Ramesh   20  Hyd
1  Suresh   22  Mum
B  Satish   40  Blr

In [56]:
#create new dataframe
l=[i for i in range(1,11)]
l1=[i^2 for i in range(1,11)]
l2=[i^3 for i in range(1,11)]

In [57]:
df=pd.DataFrame(zip(l,l1,l2),columns=['X','Y','Z'])
df

    X   Y   Z
0   1   3   2
1   2   0   1
2   3   1   0
3   4   6   7
4   5   7   6
5   6   4   5
6   7   5   4
7   8  10  11
8   9  11  10
9  10   8   9

In [58]:
#check 
#len,shape,size,head,tail,isnull,dtypes,info

In [59]:
len(df)

10

In [60]:
df.size

30

In [61]:
df.shape

(10, 3)

In [62]:
df.isnull()

       X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [63]:
df.dtypes
#if any category column occurs it will occur as object
#int will represnt as int64

X    int64
Y    int64
Z    int64
dtype: object

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [65]:
df.head()

   X  Y  Z
0  1  3  2
1  2  0  1
2  3  1  0
3  4  6  7
4  5  7  6

In [66]:
df.tail()

    X   Y   Z
5   6   4   5
6   7   5   4
7   8  10  11
8   9  11  10
9  10   8   9

In [67]:
df.isnull().sum()

X    0
Y    0
Z    0
dtype: int64

**step-15 select columns**

In [68]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [69]:
df['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [70]:
df[['X','Y']]

    X   Y
0   1   3
1   2   0
2   3   1
3   4   6
4   5   7
5   6   4
6   7   5
7   8  10
8   9  11
9  10   8

In [71]:
type(df['X'])

pandas.core.series.Series

In [72]:
type(df[['X','Y']])

pandas.core.frame.DataFrame

In [73]:
df['X'].shape

(10,)

In [74]:
df[['X','Y']].shape

(10, 2)

- df  dataframe

- df['Z'] selecting particular column

- df['Z'].values() extracting values 

- df['Z'].vales.tolist()

In [75]:
df['X']       #selecting one particular column
df['X'].values #extracting values from column
df['X'].values.tolist() #extracing and converting value to list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [76]:
df[['X','Y']]
df[['X','Y']].values

array([[ 1,  3],
       [ 2,  0],
       [ 3,  1],
       [ 4,  6],
       [ 5,  7],
       [ 6,  4],
       [ 7,  5],
       [ 8, 10],
       [ 9, 11],
       [10,  8]])