In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
file_path=r'C:\Users\vijay\Documents\NareshIT\numpy\bank.csv'
#pd.read_csv('bank.csv',se)
pd.read_csv(file_path,sep=';')

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

**do this checks while reading dataframe**

- shape

- size

- len

- columns

- dtypes

- isnull

- head

- tail

- info

In [5]:
#pd.read_csv('Visadataset.csv')
file_path=r'C:\Users\vijay\Documents\NareshIT\numpy\Visadataset.csv'
visa_df=pd.read_csv(file_path)

In [6]:
visa_df.shape

(25480, 12)

In [7]:
print(f'Number of rows in Visa dataset are : ',visa_df.shape[0] )
print(f'Number of columns in Visa dataset are : ',visa_df.shape[1] )

Number of rows in Visa dataset are :  25480
Number of columns in Visa dataset are :  12

In [8]:
visa_df.size

305760

In [9]:
len(visa_df) #number of rows

25480

In [10]:
visa_df.head(5) #top 5 rows

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [11]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [12]:
visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [13]:
visa_df.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
visa_df.isnull().sum()

case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64

In [15]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [16]:
type(visa_df)

pandas.core.frame.DataFrame

In [17]:
type(visa_df.dtypes)

pandas.core.series.Series

**task 1 **

- Seperate the categorical and numerical column

- Categorical column 

- Numerical colums

In [18]:
visa_df
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [20]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [21]:
cols=visa_df.dtypes.keys().tolist()

In [24]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [25]:
dtype=visa_df.dtypes.values.tolist()

In [26]:
cols

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [27]:
dtype

[dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O')]

In [28]:
visa_df
visa_df.dtypes
visa_df.dtypes.keys()
cols=visa_df.dtypes.keys().tolist()
dtype=visa_df.dtypes.values.tolist()

In [29]:
cat=[]
num=[]
for i,j in zip(dtype,cols):
    if i=='object':
        cat.append(j)
    else:
        num.append(j)

In [30]:
cat=[j for i,j in zip(dtype,cols) if i=='object']
num=[j for i,j in zip(dtype,cols) if i !='object']

In [31]:
print(cat)

['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status']

In [32]:
print(num)

['no_of_employees', 'yr_of_estab', 'prevailing_wage']

In [26]:
# for i,j in zip(dtype,cols):
#     if i!='object':
#         num.append(j)

In [34]:
len(cat),len(num)

(9, 3)

In [35]:
visa_df
visa_df.dtypes
visa_df.dtypes.keys()
cols=visa_df.dtypes.keys().tolist()
dtype=visa_df.dtypes.values.tolist()
cat=[j for i,j in zip(dtype,cols) if i=='object']
num=[j for i,j in zip(dtype,cols) if i !='object']
len(cat),len(num)

(9, 3)

**select dtypes**

In [36]:
visa_df.select_dtypes(exclude='object')
num=visa_df.select_dtypes(exclude='object')
cat=visa_df.select_dtypes(include='object')

In [37]:
len(cat),len(num)

(25480, 25480)

**convert series to dataframe**

In [38]:
dtypes=visa_df.dtypes
d1=pd.DataFrame(dtypes,columns=['Data types'])
d1.reset_index().rename(columns={'index':'Column'})

                   Column Data types
0                 case_id     object
1               continent     object
2   education_of_employee     object
3      has_job_experience     object
4   requires_job_training     object
5         no_of_employees      int64
6             yr_of_estab      int64
7    region_of_employment     object
8         prevailing_wage    float64
9            unit_of_wage     object
10     full_time_position     object
11            case_status     object

In [39]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [40]:
visa_df.dtypes.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [41]:
dict(visa_df.dtypes)

{'case_id': dtype('O'),
 'continent': dtype('O'),
 'education_of_employee': dtype('O'),
 'has_job_experience': dtype('O'),
 'requires_job_training': dtype('O'),
 'no_of_employees': dtype('int64'),
 'yr_of_estab': dtype('int64'),
 'region_of_employment': dtype('O'),
 'prevailing_wage': dtype('float64'),
 'unit_of_wage': dtype('O'),
 'full_time_position': dtype('O'),
 'case_status': dtype('O')}

In [37]:
cols=visa_df.dtypes.index.tolist()
dtype=visa_df.dtypes.values.tolist()
pd.DataFrame(zip(cols,dtype))

                        0        1
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

**selection of data**

In [38]:
#visa_df.iloc[rows,columns]
#visa_df.iolc[start:stop:step,start:stop:step]
visa_df.iloc[100:105,3:6]  #100 to 104 row and 3 to 5 columns
visa_df.iloc[100:105]      # 100 to 105 rows and all colums  
visa_df.iloc[100]          #100th rows in series type
visa_df.iloc[[100]]        #100th row in dataframe type

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [39]:
visa_df.iloc[[100,200,300]]        #100th, 200th and 300th row in dataframe type

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [40]:
visa_df.iloc[[100,200,300],3:6]

    has_job_experience requires_job_training  no_of_employees
100                  Y                     N             2227
200                  Y                     N             3282
300                  Y                     N             3268

In [41]:
visa_df.iloc[[100,200,300],[1,3,9]]

    continent has_job_experience unit_of_wage
100      Asia                  Y         Year
200      Asia                  Y         Year
300      Asia                  Y         Year

In [42]:
visa_df.loc[[100,200,200],['continent', 'no_of_employees','has_job_experience']]

    continent  no_of_employees has_job_experience
100      Asia             2227                  Y
200      Asia             3282                  Y
200      Asia             3282                  Y

In [43]:
cols.index('unit_of_wage')

9

In [44]:
cols

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']