**feature encoding**

- so we have perform feature analysis

    - datafram quick checks

    - categorical column analysis

    - bar chart and pie chart

    - numerical column analysis

    - histogram, box plot, outlier

    - Bi multi variant analysis

    - correlation etc

- Now we need to learn Feature Engineering

    - we will create new column for better ML analysis

    - We will perform **encoding** that is converting categorical column to numerical

    - we will do data **transformation**

    - we will perform **Scaling: Sandardaziation and Normalization**

    - We will perform the **missing value analysis**

- Simply feature engineering means our data will be modified

In [1]:
#11-12-2025

- feature analysis

- feature engineering

- feature selection

- model development

- model testing/evaluation

- model tuning 

- model deployment

**endcoding**

- Encoding convert categorical data to numerical data

- ML/DL or any model works based on math

- models does not understand english character

- so it is important to convert categorical column to number 

- For example Geneder column has two labels

   - male 
   - female

- so female represent 0 and male 1 based on aplabetical order

-

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
file_path=r'C:\Users\vijay\Documents\NareshIT\data_files\Visadataset.csv'

In [4]:
visa_df=pd.read_csv(file_path)

In [5]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

- Certified should assign 0

- Denied should assign 1

In [6]:
d={'Certified':0, 'Denied':0}
d

{'Certified': 0, 'Denied': 0}

In [7]:
visa_df['case_status']=visa_df['case_status'].map(d)

In [8]:
#visa_df

In [9]:
labels=visa_df['continent'].unique()

In [10]:
labels=sorted(labels)
n=len(labels)

In [11]:
labels

['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']

In [12]:
file_path=r'C:\Users\vijay\Documents\NareshIT\data_files\Visadataset.csv'
visa_df=pd.read_csv(file_path)
labels=visa_df['continent'].unique()
labels=sorted(labels)
n=len(labels)
d={}
for i in range(n):
    d[labels[i]]=i
#visa_df['continent']=visa_df['continent'].map(d)
#visa_df
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [13]:
visa_df['continent']=visa_df['continent'].map(d)
#visa_df

In [14]:
#visa_df['continent']=visa_df['continent'].map(d)

In [15]:
file_path=r'C:\Users\vijay\Documents\NareshIT\data_files\Visadataset.csv'
visa_df=pd.read_csv(file_path)
labels=visa_df['continent'].unique()
labels=sorted(labels)
d={}
for i,j in enumerate(labels):
     d[j]=i

In [16]:
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [17]:
visa_df['continent']=visa_df['continent'].map(d)

In [18]:
#visa_df

In [19]:
labels=visa_df['continent'].unique()
d={}
for i,j in enumerate(labels):
     d[j]=i
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [20]:
for i,j in enumerate(labels):
    print(i,j)

0 1
1 0
2 3
3 2
4 5
5 4

In [21]:
file_path=r'C:\Users\vijay\Documents\NareshIT\data_files\Visadataset.csv'
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns
for i in cat[1:]:
    labels=sorted(visa_df[i].unique())
    d={j:i for i,j in enumerate(labels)}
    visa_df[i]=visa_df[i].map(d)

In [22]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**LableEncoder**

- LableEncoder is method which will convert cat lables to numerica lables

- it under the package sklearn(scikit-learn)

    - The class name :**preprocessing**

        - The method name LableEncoder

In [23]:
from sklearn.preprocessing import LabelEncoder

- step -1 import method

- step -2 save the method

- step -3 apply fit transform

- **fit transform**

    - **fit** means find the logic

        - in above example fit means created **mapper** or **dict**
    
    - **transform** apply the logic and change the data

        - apply the mapper on data

In [24]:
file_path=r'C:\Users\vijay\Documents\NareshIT\data_files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

#import the method**
from sklearn.preprocessing import LabelEncoder
#save the method
le=LabelEncoder()
#apply the mapper
le.fit_transform(visa_df['case_status'])
visa_df['case_staus']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_staus
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [25]:
from sklearn.preprocessing import LabelEncoder
#save the method
le=LabelEncoder()
#apply the mapper
le.fit_transform(visa_df['continent'])
visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_staus
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [26]:
from sklearn.preprocessing import LabelEncoder
cat=visa_df.select_dtypes(include='object').columns
le=LabelEncoder()
for i in cat:
    print(i)
    visa_df[i]=le.fit_transform(visa_df[i])
visa_df

case_id
education_of_employee
has_job_experience
requires_job_training
region_of_employment
unit_of_wage
full_time_position
case_status

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_staus
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0,0

**OnehotEncoder**

- First how many labels are there in columns

- That many new columns will be created extra

- for example case_status has two labels

    - Certified

    - Denied

- it will create two new extra columns

    - case_status_Certified

    - case_status_Denied

- at a time one column value become 1 and another columns value becomes zero

- This means one hot encoder

- continet
- Asia
- Africa
- Euroe

- three new columns weil be created

-  C_A        C_Af          C_Eu

-    1          0             0
-    0          1             0
-    0          0             1

**pd.get_dummeis**

In [29]:
file_path=r'C:\Users\vijay\Documents\NareshIT\data_files\Visadataset.csv'
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns
pd.get_dummies(visa_df['case_status'],dtype=int)
pd.get_dummies(visa_df['continent'],dtype=int)

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]